version: 0.8.{build}
environment:
  matrix:
  - Configuration: Debug
    Platform: Win32
    BuildEngine: vc
  - Configuration: Release
    Platform: Win32
    BuildEngine: vc
before_build:
- cmd: >-
    if "%platform%" == "x64" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
    if "%platform%" == "x64" (set qtplatform=msvc2015_64) else (set qtplatform=msvc2015)
    "C:\Qt\5.7\%qtplatform%\bin\qmake.exe" -r -tp "%buildengine%"
build:
  parallel: true
  verbosity: minimal
test_script:
- ps: >-
    if($env:platform -eq "x64") {
        $env:path = "C:\Qt\5.7\msvc2015_64\bin"
    } else {
        $env:path = "C:\Qt\5.7\msvc2015\bin"
    }
    ls "Tests\$env:Configuration" -filter "*.exe" |
    % { 
        $filename = $_.FullName
        &$filename "-functions" |
        % {
            $testName = $_.trim("()")
            Add-AppveyorTest -Name $testName -Framework "xUnit" -Filename $filename -Outcome "Running"
            &$filename $testName
            if($LastExitCode -eq 0)
            {
                $result = "Passed"
            }
            else
            {
                $result = "Failed"
            }
            Update-AppveyorTest -Name $testName -Framework "xUnit" -Filename $filename -Outcome $result
        }
    }
artifacts:
- path: App\$(configuration)\*.exe